"""Regenerate requirements.lock from the current environment.

Usage: python scripts/freeze.py
Excludes the project itself and eval-only tooling (the sklearn stack used
for one-off similarity calibration, never a runtime dependency).
"""

from __future__ import annotations

import sys
from importlib import metadata
from pathlib import Path

EVAL_ONLY = {
    "scikit-learn",
    "scipy",
    "joblib",
    "threadpoolctl",
    "narwhals",
    "cloudpickle",
    "insightface-ray-serve-api",
}

HEADER = """\
# Full transitive dependency lock for containers and reproducible installs.
# Generated by `python scripts/freeze.py` from a verified working environment.
# Direct pins also live in pyproject.toml; this file adds transitive pins.
# Eval-only tooling (scikit-learn stack) is excluded on purpose.
"""


def main() -> int:
    names = sorted({d.metadata["Name"] for d in metadata.distributions()})
    lines = [HEADER.rstrip()]
    for name in names:
        if name.lower() in EVAL_ONLY:
            continue
        try:
            lines.append(f"{name}=={metadata.version(name)}")
        except Exception as exc:  # pragma: no cover - defensive, shouldn't happen
            print(f"skip {name}: {exc}", file=sys.stderr)
    Path("requirements.lock").write_text("\n".join(lines) + "\n")
    print(f"wrote requirements.lock with {len(lines) - 1} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
